parameters:
#    group_topics_frontend.example.class: GroupTopics\FrontendBundle\Example

services:
#    group_topics_frontend.example:
#        class: %group_topics_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
