parameters:
#    group_topics_account.example.class: GroupTopics\AccountBundle\Example

services:
#    group_topics_account.example:
#        class: %group_topics_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
