parameters:
#    gt_public.example.class: SDPHP\Gt\PublicBundle\Example

services:
#    gt_public.example:
#        class: %gt_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
