SDPHP\Gt\PublicBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        emailaddress:
            type: string
            length: 255
        password:
            type: string
            length: 255
        username:
            type: string
            length: 255
    lifecycleCallbacks: {  }
